### PR TITLE
Jupyter Hub

### PR DESCRIPTION
**Pull request by adrianq**

### CODE REVIEW

**Comment by rodriguez-facundo** [comment]
The way this works at the moment is by hardcoding a path to `/src/main/webapp/build`.
With the new schema, we can not longer hardcode paths because we don't know beforehand the name of the application (and the build folder now belongs to geppetto-application). So it might be the case that someone decides to use the geppetto-application repo as a template to build, let's say, geppetto-my_awesome_app. Then, tornado will need a path like this one:
`geppetto-my_aswesome_app/build` instead of `src/main/webapp/buil`.

the way I went about this (and you can check it on `feature-split_dependencies` branch) is by using a jupyter notebook extra config `config['app_relative_path']`. 

So, at the moment, we launch notebooks with this command:

`jupyter notebook --NotebookApp.default_url=/geppetto --NotebookApp.token='' --library=netpyne_ui`

In my proposal, we will do it like this:

`jupyter notebook --NotebookApp.default_url=/geppetto --NotebookApp.token='' --library=netpyne_ui --app_relative_path=../geppetto-my_awesome_app`

**Comment by tarelli** [comment]
@rodriguez-facundo we are going to need to have more than one app configured there, I was thinking something along the lines of the library parameter starts accepting an array and we loop inside it inside __init__.py. If now we have the relative path (and I see why it's necessary) the way I understand this we'll need to also have an array there. Would that solve it? And if the answer is yes I'd next try to understand if there's a better way of doing this (referred to having two arrays).

**Comment by rodriguez-facundo** [comment]
The way I like to think about this is that now we have apps that stand by themselves.  So when you launch a new notebook, that notebook needs to know which app would you like to run. It is within that framework that I like the idea of adding an extra parameter to the way in which you launch notebooks.

Now, if you are in a folder where you have multiple apps, you can decide which one to launch in the next notebook by doing:

`jupyter notebook --app_relative_path=../geppetto-my_awesome_app`

Now you decide to test another app, then you run:

`jupyter notebook --app_relative_path=../geppetto-my_other_app`

I can even remove the `../` so that you only need to pass the name of the app that you would like to launch next.

That is the way I have been switching between geppetto-application and geppetto-netpyne this time in order to test them. 

I guess the thing I did not explain very well is that it does not exist a place where you store the paths of your apps. It is just a dynamic argument that you have to pass at the moment of launching the notebook. 

Does this make sense?

**Comment by tarelli** [comment]
@rodriguez-facundo the thing is we are talking about having multiple apps started, each would add their rest APIs and url eg localhost:888/app1 localhost:888/app2 and they share the same Python Kernel underneath.

**Comment by rodriguez-facundo** [comment]
Ok, no problem. The idea might be to have something along the line what jupyter already provides:
screen shot 2019-02-05 at 14 29 29
You click `new` and then you choose your `app`.

But I would like to take care of something like that in the future, after closing jupyterhub, and closing split_dependencies.

**Pull request merged**
